#!/system/bin/sh

# remount /system

#echo "uninstall.sh was called" > /data/local/tmp/call.log

if [ -f /system/xbin/su ]
then
	mount -o remount,rw /system
	rm /system/xbin/su
	mount -o remount,ro /system
fi
