#!/system/bin/sh

/system/etc/su_client -c "/system/etc/busybox_file mount -o remount,rw /system"
/system/etc/su_client -c "/system/etc/busybox_file cp /system/etc/su_client /system/xbin/su"
/system/etc/su_client -c "chown root.root /system/xbin/su"
/system/etc/su_client -c "chmod 755 /system/xbin/su"
/system/etc/su_client -c "/system/etc/busybox_file mount -o remount,ro /system"
